'use strict';

const { compileFast } = require('struct-compile');
const { READ_STRUCT } = require('./ops');

/*
 * Struct codegen — thin adapter over struct-compile's fast mode.
 *
 * `cstruct(src)` feeds a C-style struct source verbatim to struct-compile
 * and wraps every declared struct into an Engine-compatible op:
 *
 *   const { PacketHeader } = cstruct(`
 *     //@LE
 *     struct __attribute__((__packed__)) PacketHeader {
 *       uint32_t tv_sec;
 *       uint32_t tv_usec;
 *       uint32_t caplen;
 *       uint32_t len;
 *     };
 *   `);
 *
 *   yield PacketHeader;          // engine reads `PacketHeader.size` bytes,
 *                                // dispatches to decodeLE/decodeBE, yields
 *                                // a plain object with monomorphic shape.
 *   PacketHeader.encodeLE(buf, off, value);
 *
 * The decode/encode functions are generated by struct-compile (literal
 * object with constant field offsets compiled via `new Function`); this
 * module only adds the `READ_STRUCT` tag and a `write(frame, value)` helper
 * so the writer side can target a `FrameBuilder`.
 */

function wrap(compiled) {
  return {
    tag:      READ_STRUCT,
    size:     compiled.size,
    decodeLE: compiled.decodeLE,
    decodeBE: compiled.decodeBE,
    encodeLE: compiled.encodeLE,
    encodeBE: compiled.encodeBE,
    write(frame, value) {
      frame.ensure(this.size);
      const enc = frame.endian === 'LE' ? this.encodeLE : this.encodeBE;
      enc(frame.buf, frame.off, value);
      frame.off += this.size;
    },
  };
}

function cstruct(src) {
  const compiled = compileFast(src);
  const out = {};
  for (const name of Object.keys(compiled)) out[name] = wrap(compiled[name]);
  return out;
}

module.exports = { cstruct };
