Napi::Object InitSystemLocal(Napi::Env env, Napi::Object exports) {
  ENUM_VALUE(AF_UNSPEC);
  ENUM_VALUE(AF_INET);
  ENUM_VALUE(AF_IPX);
  ENUM_VALUE(AF_APPLETALK);
  ENUM_VALUE(AF_NETBIOS);
  ENUM_VALUE(AF_INET6);
  ENUM_VALUE(AF_IRDA);
  ENUM_VALUE(AF_BTH);

  ENUM_VALUE(SOCK_STREAM);
  ENUM_VALUE(SOCK_DGRAM);
  ENUM_VALUE(SOCK_RAW);
  ENUM_VALUE(SOCK_RDM);
  ENUM_VALUE(SOCK_SEQPACKET);

  ENUM_VALUE(IPPROTO_ICMP);
  ENUM_VALUE(IPPROTO_IGMP);
  //ENUM_VALUE(BTHPROTO_RFCOMM);
  ENUM_VALUE(IPPROTO_TCP);
  ENUM_VALUE(IPPROTO_UDP);
  ENUM_VALUE(IPPROTO_ICMPV6);
  //ENUM_VALUE(IPPROTO_RM);
  ENUM_VALUE(IPPROTO_IP);
  ENUM_VALUE(IPPROTO_GGP);
  ENUM_VALUE(IPPROTO_IPV4);
  ENUM_VALUE(IPPROTO_ST);
  ENUM_VALUE(IPPROTO_CBT);
  ENUM_VALUE(IPPROTO_EGP);
  ENUM_VALUE(IPPROTO_IGP);
  ENUM_VALUE(IPPROTO_PUP);
  ENUM_VALUE(IPPROTO_IDP);
  ENUM_VALUE(IPPROTO_RDP);
  ENUM_VALUE(IPPROTO_ND);
  ENUM_VALUE(IPPROTO_ICLFXBM);
  ENUM_VALUE(IPPROTO_PIM);
  ENUM_VALUE(IPPROTO_PGM);
  ENUM_VALUE(IPPROTO_L2TP);
  ENUM_VALUE(IPPROTO_SCTP);
  ENUM_VALUE(IPPROTO_RAW);

  ENUM_VALUE(SO_BROADCAST);
  ENUM_VALUE(SO_CONDITIONAL_ACCEPT);
  ENUM_VALUE(SO_EXCLUSIVEADDRUSE);
  ENUM_VALUE(SO_KEEPALIVE);
  ENUM_VALUE(SO_RCVBUF);
  ENUM_VALUE(SO_REUSEADDR);

  return exports;
}
